[package]
name = "krieg"
version = "0.1.0"
authors = ["jon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.sdl2]
version = "*"
defaut-features = false
features = ["image"]
